# Bulgular tabloları (veri: analiz/stats-insan.json, ana set n = 363; korpus-belge/*/_envanter.csv).
# Her tablo, metinde "(Tablo N)" ifadesinin ilk geçtiği paragrafın hemen ardından yerleştirilir.
TABLOLAR = {
    1: {"baslik": "İncelenen Belgelerin Bileşimi",
        "sutunlar": ["Belge grubu", "Türk", "Çin", "Ortak", "Belge", "Anlam birimi"],
        "satirlar": [["İkili belgeler", "11", "12", "2", "25", "179"],
                     ["Tek taraflı belgeler", "12", "12", "0", "24", "189"],
                     ["Toplam", "23", "24", "2", "49", "368"]],
        "not": "Analiz, üç kodlamanın da farklı alan verdiği 5 birim çıkarıldıktan sonra 363 birim üzerinden yapılmıştır."},
    2: {"baslik": "Belge Gruplarına Göre Yönelim",
        "sutunlar": ["Belge grubu", "n", "İş birliği", "Rekabet", "Karma", "Nötr", "İş birliği %", "Rekabet %"],
        "satirlar": [["İkili belgeler", "177", "88", "36", "3", "50", "49,7", "20,3"],
                     ["Tek taraflı belgeler", "186", "51", "40", "3", "92", "27,4", "21,5"]],
        "not": "Yüzdeler tüm birimler üzerinden hesaplanmıştır. Duyarlılık (iş birliği % / rekabet %): birinci kodlayıcı ikili 46,9/17,9, tek taraflı 17,5/27,0; ikinci kodlayıcı ikili 45,3/21,2, tek taraflı 35,4/16,9; iki kodlayıcının uyuştuğu birimler (n = 195) ikili 54,7/17,9, tek taraflı 29,2/20,2."},
    3: {"baslik": "Alanlara Göre Yönelim ve Rekabet Payı",
        "sutunlar": ["Alan", "n", "İş birliği", "Rekabet", "Karma", "Nötr", "Rekabet % (nötr hariç)", "Rekabet % (nötr dahil)"],
        "satirlar": [["Bağlantısallık", "98", "45", "21", "0", "32", "31,8", "21,4"],
                     ["Turist akışı", "123", "49", "30", "3", "41", "36,6", "24,4"],
                     ["Anlatı", "122", "40", "21", "3", "58", "32,8", "17,2"],
                     ["Değer yakalama", "20", "5", "4", "0", "11", "44,4", "20,0"]],
        "not": "Alanlar turiste yakınlık sırasına göre (üstten alta artan) analizden önce sıralanmıştır."},
    4: {"baslik": "Ö3 Karar Kuralının Farklı Kodlama Setlerindeki Sonucu (Rekabet %, Nötr Hariç)",
        "sutunlar": ["Kodlama seti", "Bağlantısallık", "Turist akışı", "Anlatı", "Değer yakalama", "Fark", "Karar"],
        "satirlar": [["Çoğunluk (n = 363)", "31,8", "36,6", "32,8", "44,4", "+12,6", "Kısmi"],
                     ["Çoğunluk, nötr dahil", "21,4", "24,4", "17,2", "20,0", "−1,4", "Destek yok"],
                     ["Birinci kodlayıcı", "41,9", "35,6", "40,3", "33,3", "−8,6", "Destek yok"],
                     ["İkinci kodlayıcı", "22,0", "37,6", "31,8", "33,3", "+11,3", "Kısmi"],
                     ["Uyuşulan birimler (n = 195)", "16,7", "36,7", "33,3", "25,0", "+8,3", "Kısmi"]],
        "not": "Karar kuralı (analizden önce yazıldı): düzenli artış ya da bağlantısallık ile değer yakalama arasındaki farkın en az 20 yüzde puan olması destek; farkın sıfır ya da negatif olması destek yok; arası kısmi destek."},
    5: {"baslik": "Kaynak Tarafına Göre Rekabet Payı (%, Nötr Hariç)",
        "sutunlar": ["Kaynak", "Bağlantısallık", "Turist akışı", "Anlatı", "Değer yakalama", "Kendini öne çıkarma %", "Dışlama %"],
        "satirlar": [["Türk kaynakları (n = 154)", "45,0", "56,2", "55,6", "75,0", "20,8", "13,6"],
                     ["Çin kaynakları (n = 195)", "13,0", "25,0", "24,4", "25,0", "9,2", "6,2"]],
        "not": "Ortak belgelerden gelen 14 birim bu tabloya dahil edilmemiştir. Türk kaynaklarında değer yakalama alanındaki değer yalnızca dört birime dayanmaktadır."},
}
